apiVersion: apps/v1
kind: Deployment
metadata:
  name: app8-microservice3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app8-microservice3
  template:
    metadata:
      labels:
        app: app8-microservice3
    spec:
      containers:
      - name: app8-microservice3
        image: b0rkemborina/zta-cybersec-suite:app8microservice3
        ports:
        - containerPort: 8072